### ISSUE TITLE
cloining on windows -> "aux.rst" file interrupting

### ISSUE THREAD

**Issue by Yarden92** [xmhk/FNFTpy#2]
Windows doesn't like files named aux, 
so the file "documentation/sphinx/source/aux.rst" stopping with error the ```git clone https://github.com/xmhk/FNFTpy.git``` process.

Is this file mandatory?
can it be renamed / removed?

**Comment by xmhk** [comment]
Hi Yarden,
that is indeed a weird behavior. The file aux.rst is only needed to create the documentation file via sphinx. It can be renamed or deleted (I renamed it in the latest push).
Best, Christoph
