### ISSUE TITLE
nsev_inverse is not aligned with MATLAB version

### ISSUE THREAD

**Issue by Yarden92** [xmhk/FNFTpy#5]
I'm trying to match my code with my professor's MATLAB version
in his code he calls nsev_inverse with the following command:

`qin=mex_fnft_nsev_inverse(bin_padded, XI, [], [], Nnft, tau, 1,'cstype_b_of_xi');`

where:

- bin_padded is a complex vector over xi domain, length Nnft
- XI =  [-511.9375  512.0000]
- Nnft = 16384
- tau = -25.1297   25.1327

my python version of it is:
```
res = nsev_inverse(xi_padded, t_padded, bin_padded,[], [],  cst=1, dst=0)
qin = res['q']
```

where 
- xi_padded is vector starting from -511.9375 to 511.9375 (length 16384)
- t_padded: [-25.13274123, ...,  25.12353734] (length 16384)
- input bin_padded is 1-1 the same as the MATLABs (verified)

the description says:

    * cst : type of continuous spectrum, default = 0

        * 0 = Reflection coefficient
        * 1 = b of xi
        * 2 = b of tau

so I chose cst=1 (sounds pretty straight forward)

but the output phase is different:
<img width="706" alt="image" src="https://github.com/xmhk/FNFTpy/assets/19271465/a96ca158-afcd-43bf-847b-53464c7bf6c9">

I tried messing up with the params but no luck

**Comment by Yarden92** [comment]
maybe I'm wrong.. double checking.. closing for now

**Comment by wahls** [comment]
Dear @Yarden92,

Could you post a fully functional code example that reproduces the problem? That is, a script that can be run directly?

Best, Sander

**Comment by Yarden92** [comment]
while trying to write a simple code that demonstrate that I found my bug.. it was indexing problem (of matlab starting with 1 and python with 0) that caused the issue..

after fixing it I got back 1-1 results of matlab vs python..

closing this issue,
thanks and sorry for the mistake, hope I didn't waste too much of your time trying to figure it out..

**Comment by wahls** [comment]
No worries.
